### ISSUE TITLE
adob vs. popwin incompatibility

### ISSUE THREAD

**Issue by fischman** [mina86/auto-dim-other-buffers.el#10]
The code snippet below results in the *Help* buffer being dimmed even though it has keyboard focus, i.e. if I type C-f cursor moves forward in *Help* and *Help* becomes undimmed.
I think I only see this behavior with popwin in the mix, but can't swear to it.

```
(progn
  (load "~/.emacs.d/elpa/auto-dim-other-buffers-20160128.946/auto-dim-other-buffers.el")
  (auto-dim-other-buffers-mode 1)
  (load "~/.emacs.d/elpa/popwin-20150315.600/popwin.el")
  (popwin-mode 1)
  (describe-key (kbd "SPC")))
```

(BTW thanks for writing adob; it's great!)

**Comment by mina86** [comment]
Yes, I can reproduce this behaviour, but to be honest I don’t know when I’ll have the time to fix this.

**Comment by fischman** [comment]
Took a crack at it this evening and reduced to a case where (current-buffer) returns a stale value after describe-key returns, with neither popwin nor adob in the mix.  Reported to emacs-devel.

```
(progn
  (setq display-buffer-alist '(("." (lambda (buffer alist) (switch-to-buffer buffer)))))
  (setq pre (current-buffer))
  (describe-key (kbd "SPC"))
  (setq post (current-buffer))
  (run-at-time 0 nil (lambda () (message "%s %s %s" pre post (current-buffer)))))
```

**Comment by fischman** [comment]
FTR emacs-devel thread: https://lists.gnu.org/archive/html/emacs-devel/2016-10/msg00043.html

Thanks for the fix!

**Comment by alphapapa** [comment]
This is very late, but thanks to both of you for fixing this.  I had noticed this bug for a long time but never bothered to investigate.  I just noticed that there was a newer version of this package, I installed it, and now it's fixed!  :D
