### ISSUE TITLE
Is there a way to customize fringes too?

### ISSUE THREAD

**Issue by angrybacon** [mina86/auto-dim-other-buffers.el#11]
It looks fringes are frame dependant. I can't find a way to have the fringe dimmed too.

**Comment by mina86** [comment]
None that I am aware of.

**Comment by angrybacon** [comment]
Pretty late, but just in case someone stumbled upon this:

```elisp
(setq-default
 left-margin-width 1
 right-margin-width 1)
(fringe-mode 0)
```

This disables the fringes and use margins instead for spacing around buffer content.

**Comment by QiangF** [comment]
@angrybacon Can you share with us how did you highlight the current window in this way?

**Comment by angrybacon** [comment]
@QiangF What do you mean specifically? I don't use `auto-dim-other-buffers` anymore but I just reinstalled it to test the code above and it worked with no additional customization.

**Comment by QiangF** [comment]
@angrybacon I thought you can dim (or hightlight) the fringe (or margin) instead of the whole buffer. Now I see. But I think it's a better way to high light the margin of the current buffer for the purpose of easily find it than dim all others.
