### ISSUE TITLE
Feature request: don't dim last buffer when focus switches to minibuffer

### ISSUE THREAD

**Issue by sandinmyjoints** [mina86/auto-dim-other-buffers.el#14]
Currently, if point is in the minibuffer, then the minibuffer is undimmed and all other buffers are dimmed. It'd be great to have an option to leave undimmed whatever buffer point was in before it went into the minibuffer. (I imagine not everyone would want this, which is why it'd make a good option, not default.)

From glancing at the code, thoughts:
- On focus out, if new buffer is minibuffer, then don't dim last buffer. But on focus out, do we know new buffer? Maybe not. 
- So instead, on focus in, if current-buffer is minibuffer, undim adob--last-buffer before updating adob--last-buffer to current-buffer.

**Comment by sandinmyjoints** [comment]
I thought this might do it but it doesn't seem to work:

```diff
--- 2.el	2017-09-24 22:01:00.000000000 -0700
+++ 1.el	2017-09-24 22:00:53.000000000 -0700
@@ -2,4 +2,8 @@
   "Undim current buffers if `auto-dim-other-buffers-dim-on-focus-out'."
   (when auto-dim-other-buffers-dim-on-focus-out
     (adob--dim-buffer nil)
+    ;; if current-buffer is minibuffer, then undim last buffer.
+    (when (minibufferp (current-buffer))
+      (with-current-buffer adob--last-buffer
+        (adob--dim-buffer nil)))
     (setq adob--last-buffer (current-buffer))))
```

**Comment by mina86** [comment]
`adob--focus-out-hook` is called when Emacs frame (i.e. window in X11 or Windows terms) looses focus. To affect what happens when window is changed, `adob--buffer-list-update-hook` needs to be played with.

**Comment by sandinmyjoints** [comment]
Thanks!
