### ISSUE TITLE
auto-dim doesn't work for find-file-other-window

### ISSUE THREAD

**Issue by tautologyclub** [mina86/auto-dim-other-buffers.el#17]
Hey,

I use adob-mode all the time, but it doesn't handle some fringe cases well. Specifically find-file-other-window and similar functions. This is true even if I write something that manually triggers the adob--dim-buffer functions. I guess it's because there's some confusion about which window is currently focused when this occurs. Any ideas on how to resolve this?

**Comment by mina86** [comment]
Could you provide reproduction steps? `M-x view-lossage RET` might help with that.

**Comment by tautologyclub** [comment]
I can't reproduce any more. Weird.

**Comment by mina86** [comment]
I cannot reproduce it either so closing for now. If this happens again `view-lossage` output might be helpful.
