### ISSUE TITLE
Focused buffer window gets dimmed when using centaur-tabs

### ISSUE THREAD

**Issue by maronin** [mina86/auto-dim-other-buffers.el#20]
When using [centaur-tabs ](https://github.com/ema2159/centaur-tabs) package with auto-dim-other-buffers, focused window randomly get dimmed.

I am not sure why this happens. Can anyone point me in the right direction to debug this? I really want to use this package combined >.<

Thank you so much!

**Comment by mina86** [comment]
I had a go with the centaur-tabs for a few days and couldn’t reproduce the issue. This could be related to change I’ve just committed which improves auto-dim-other-buffers when run under Emacs 27.1 or newer. Could you check if you can reproduce the issue when running newest adob on most recent Emacs?
