### ISSUE TITLE
Let it work with Emacs 27 prerelease

### ISSUE THREAD

**Issue by fishyfriend** [mina86/auto-dim-other-buffers.el#21]
Would it be possible to change the Emacs 27.1 version check to include all v27 prereleases, at least as early as 27.0.91?

I'm interested in using the new window-dimming (as opposed to buffer-dimming) behavior but not interested in compiling emacs myself, so I'm using the prerelease version 27.0.91 provided by my OS (Guix). I know there are many folks using 27 already and suspect they could be in the same boat.

I know the functionality works in 27.0.91 because when I put `(setq emacs-version "27.1.0")` at the top of my init file, auto-dim-other-buffers engages its window-dimming behavior successfully. I.e., if I have two windows displaying the same buffer, the inactive one will be dimmed while the active one displays normally. This isn't practical though, as faking the emacs version will screw up other things.

Thanks for the useful package.

**Comment by fishyfriend** [comment]
Awesome, much appreciated!

**Comment by mina86** [comment]
n/p.
