### ISSUE TITLE
error "Marker points into wrong buffer"

### ISSUE THREAD

**Issue by xkix** [mina86/auto-dim-other-buffers.el#23]
hi, thanks vor `auto-dim-other-buffers.el`, love it.
after update to `20200704.122` using `(ispell-word)`, which is bound to `M-$`, gives the following, everything works when disabling `(auto-dim-other-buffers-mode)`:

> Debugger entered--Lisp error: (error "Marker points into wrong buffer" #<marker at 1 in my-tmp>)
>   move-overlay(#<overlay in no buffer> #<marker at 1 in my-tmp> #<marker at 6 in my-tmp> #<buffer *Choices*>)
>   (if ispell-overlay (move-overlay ispell-overlay start end (current-buffer)) (setq ispell-overlay (make-overlay start end)) (overlay-put ispell-overlay (quote priority) 1001) (overlay-put ispell-overlay (quote face) ispell-highlight-face))
>   (if highlight (if ispell-overlay (move-overlay ispell-overlay start end (current-buffer)) (setq ispell-overlay (make-overlay start end)) (overlay-put ispell-overlay (quote priority) 1001) (overlay-put ispell-overlay (quote face) ispell-highlight-face)) (if ispell-overlay (delete-overlay ispell-overlay)))
>   ispell-highlight-spelling-error-overlay(#<marker at 1 in my-tmp> #<marker at 6 in my-tmp> t)
>   (if (display-color-p) (ispell-highlight-spelling-error-overlay start end highlight) (ispell-highlight-spelling-error-generic start end highlight refresh))
>   ispell-highlight-spelling-error(#<marker at 1 in my-tmp> #<marker at 6 in my-tmp> t)
>   (and ispell-highlight-p (ispell-highlight-spelling-error start end t))
>   (progn (and ispell-highlight-p (ispell-highlight-spelling-error start end t)) (while (eq t (setq result (progn (undo-boundary) (let (message-log-max) (message (concat "C-h or ? for more options; SPC to leave " "unchanged, Character to replace word"))) (let ((inhibit-quit t) (input-valid t)) (setq char nil skipped 0) (while (and input-valid ...) (setq char ...) (setq input-valid ...)) (if (or quit-flag ... ...) (progn ...))) (let ((com-chars command-characters)) (while com-chars (if ... ...) (setq com-chars ...)) (setq num (- char 48 skipped))) (cond ((= char 32) nil) ((= char 105) (ispell-send-string ...) (setq ispell-pdict-modified-p ...) (if flyspell-mode ...) nil) ((or ... ...) (ispell-send-string ...) (setq ispell-buffer-session-localwords ...) (if flyspell-mode ...) (or ispell-buffer-local-name ...) (if ... ...) (if ... 0)) ((or ... ...) (and ... ...) (let ... ... result)) ((or ... ... ...) (and ... ...) (ispell-help) (and ... ...) t) ((= char 120) (ispell-pdict-save ispell-silently-savep) (message "Exited spell-checking") (setq ispell-quit t) nil) ((= char 88) (ispell-pdict-save ispell-silently-savep) (message "%s" ...) (setq ispell-quit start) nil) ((= char 113) (if ... ... t)) ((= char 108) (and ... ...) (let ... ...) (and ... ...) t) ((= char 117) (ispell-send-string ...) (setq ispell-pdict-modified-p ...) nil) ((= char 109) (ispell-send-string ...) (setq ispell-pdict-modified-p ...) (cons word nil)) ((and ... ...) (if ispell-query-replace-choices ... ...)) ((= char 12) (redraw-display) t) ((= char 18) (if ... ... ... ... ...) (list word nil)) ((= char 26) (funcall ...) t) (t (ding) t)))))) result)
>   (unwind-protect (progn (and ispell-highlight-p (ispell-highlight-spelling-error start end t)) (while (eq t (setq result (progn (undo-boundary) (let (message-log-max) (message ...)) (let (... ...) (setq char nil skipped 0) (while ... ... ...) (if ... ...)) (let (...) (while com-chars ... ...) (setq num ...)) (cond (... nil) (... ... ... ... nil) (... ... ... ... ... ... ...) (... ... ...) (... ... ... ... t) (... ... ... ... nil) (... ... ... ... nil) (... ...) (... ... ... ... t) (... ... ... nil) (... ... ... ...) (... ...) (... ... t) (... ... ...) (... ... t) (t ... t)))))) result) (and ispell-highlight-p (let ((wconfig (current-window-configuration))) (unwind-protect (progn (select-window textwin) (ispell-highlight-spelling-error start end)) (set-window-configuration wconfig)))))
>   (let ((count 48) (choices miss) (window-min-height (min window-min-height ispell-choices-win-default-height)) (command-characters (quote (32 105 97 65 114 82 63 120 88 113 108 117 109))) (skipped 0) char num result textwin) (save-current-buffer (set-buffer (get-buffer-create ispell-choices-buffer)) (setq mode-line-format (concat "--  %b  --  word: " word "  --  dict: " (or ispell-current-dictionary "default") "  --  prog: " (file-name-nondirectory ispell-program-name))) (with-no-warnings (setq horizontal-scroll-bar nil)) (erase-buffer) (if guess (progn (insert "Affix rules generate and capitalize " "this word as shown below:\n\011") (while guess (if (> (+ 4 ... ...) (window-width)) (progn (insert "\n\011"))) (insert (car guess) "    ") (setq guess (cdr guess))) (insert (substitute-command-keys "\nUse option `i' to accept this spelling and put it in your private dictionary.\n")))) (while choices (if (> (+ 7 (current-column) (length (car choices)) (if (> count 126) 3 0)) (window-width)) (progn (insert "\n"))) (while (memq count command-characters) (setq count (1+ count) skipped (1+ skipped))) (insert "(" count ") " (car choices) "  ") (setq choices (cdr choices) count (1+ count))) (setq count (- count 48 skipped))) (run-hooks (quote ispell-update-post-hook)) (if (not (pos-visible-in-window-group-p end)) (sit-for 0)) (setq textwin (selected-window)) (ispell-show-choices) (select-window textwin) (unwind-protect (progn (and ispell-highlight-p (ispell-highlight-spelling-error start end t)) (while (eq t (setq result (progn (undo-boundary) (let ... ...) (let ... ... ... ...) (let ... ... ...) (cond ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ...))))) result) (and ispell-highlight-p (let ((wconfig (current-window-configuration))) (unwind-protect (progn (select-window textwin) (ispell-highlight-spelling-error start end)) (set-window-configuration wconfig))))))
>   ispell-command-loop(("err ox" "err-ox" "Xerox" "xerox" "errors" "Eros" "errs" "error" "Errol" "euros" "Eric" "Rex" "Roxy" "roux" "Erik" "Eris" "epoxy" "proxy" "error's" "Errol's" "arrows" "euro's" "Eric's" "Erik's" "egos" "eras" "ergs" "approx" "Orr's" "era's" "erg's" "Eros's" "Eco's" "ego's" "arrow's" "ecru's") nil "errox" #<marker at 1 in my-tmp> #<marker at 6 in my-tmp>)
>   (setq replace (ispell-command-loop (car (cdr (cdr poss))) (car (cdr (cdr (cdr poss)))) (car poss) start end))
>   (progn (setq replace (ispell-command-loop (car (cdr (cdr poss))) (car (cdr (cdr (cdr poss)))) (car poss) start end)))
>   (unwind-protect (progn (setq replace (ispell-command-loop (car (cdr (cdr poss))) (car (cdr (cdr (cdr poss)))) (car poss) start end))) (set-window-configuration wconfig))
>   (let ((wconfig (current-window-configuration))) (unwind-protect (progn (setq replace (ispell-command-loop (car (cdr (cdr poss))) (car (cdr (cdr ...))) (car poss) start end))) (set-window-configuration wconfig)))
>   (cond ((eq poss t) (or quietly (message "%s is correct" (funcall ispell-format-word-function word)))) ((stringp poss) (or quietly (message "%s is correct because of root %s" (funcall ispell-format-word-function word) (funcall ispell-format-word-function poss)))) ((null poss) (message "Error checking word %s using %s with %s dictionary" (funcall ispell-format-word-function word) (file-name-nondirectory ispell-program-name) (or ispell-current-dictionary "default"))) (ispell-check-only (progn (beep) (message "%s is incorrect" (funcall ispell-format-word-function word)))) (t (let ((wconfig (current-window-configuration))) (unwind-protect (progn (setq replace (ispell-command-loop (car ...) (car ...) (car poss) start end))) (set-window-configuration wconfig))) (cond ((equal 0 replace) (ispell-add-per-file-word-list (car poss))) (replace (setq new-word (if (atom replace) replace (car replace)) cursor-location (+ (- (length word) (- end start)) cursor-location)) (if (not (equal new-word (car poss))) (progn (goto-char start) (insert new-word) (delete-region (point) end) (setq cursor-location (point)) (setq end (point)))) (if (not (atom replace)) (progn (if (car ...) (let ... ...)) (goto-char start) (setq ispell-quit (not ...)))))) (if (get-buffer ispell-choices-buffer) (kill-buffer ispell-choices-buffer))))
>   (let ((cursor-location (point)) (word (ispell-get-word following)) start end poss new-word replace) (setq start (car (cdr word)) end (car (cdr (cdr word))) word (car word)) (or quietly (message "Checking spelling of %s..." (funcall ispell-format-word-function word))) (ispell-send-string "%\n") (ispell-send-string (concat "^" word "\n")) (while (progn (ispell-accept-output) (not (string= "" (car ispell-filter))))) (setq ispell-filter (cdr ispell-filter)) (if (and ispell-filter (listp ispell-filter)) (if (> (length ispell-filter) 1) (error "Ispell and its process have different character maps") (setq poss (ispell-parse-output (car ispell-filter))))) (cond ((eq poss t) (or quietly (message "%s is correct" (funcall ispell-format-word-function word)))) ((stringp poss) (or quietly (message "%s is correct because of root %s" (funcall ispell-format-word-function word) (funcall ispell-format-word-function poss)))) ((null poss) (message "Error checking word %s using %s with %s dictionary" (funcall ispell-format-word-function word) (file-name-nondirectory ispell-program-name) (or ispell-current-dictionary "default"))) (ispell-check-only (progn (beep) (message "%s is incorrect" (funcall ispell-format-word-function word)))) (t (let ((wconfig (current-window-configuration))) (unwind-protect (progn (setq replace (ispell-command-loop ... ... ... start end))) (set-window-configuration wconfig))) (cond ((equal 0 replace) (ispell-add-per-file-word-list (car poss))) (replace (setq new-word (if (atom replace) replace (car replace)) cursor-location (+ (- ... ...) cursor-location)) (if (not (equal new-word ...)) (progn (goto-char start) (insert new-word) (delete-region ... end) (setq cursor-location ...) (setq end ...))) (if (not (atom replace)) (progn (if ... ...) (goto-char start) (setq ispell-quit ...))))) (if (get-buffer ispell-choices-buffer) (kill-buffer ispell-choices-buffer)))) (ispell-pdict-save ispell-silently-savep) (if ispell-quit (setq ispell-quit nil replace (quote quit))) (goto-char cursor-location) replace)
>   (cond ((and region (if t (use-region-p) (and (boundp (quote transient-mark-mode)) transient-mark-mode (boundp (quote mark-active)) mark-active (not (eq (region-beginning) (region-end)))))) (ispell-region (region-beginning) (region-end))) (continue (ispell-continue)) (t (ispell-set-spellchecker-params) (ispell-accept-buffer-local-defs) (let ((cursor-location (point)) (word (ispell-get-word following)) start end poss new-word replace) (setq start (car (cdr word)) end (car (cdr (cdr word))) word (car word)) (or quietly (message "Checking spelling of %s..." (funcall ispell-format-word-function word))) (ispell-send-string "%\n") (ispell-send-string (concat "^" word "\n")) (while (progn (ispell-accept-output) (not (string= "" (car ispell-filter))))) (setq ispell-filter (cdr ispell-filter)) (if (and ispell-filter (listp ispell-filter)) (if (> (length ispell-filter) 1) (error "Ispell and its process have different character maps") (setq poss (ispell-parse-output (car ispell-filter))))) (cond ((eq poss t) (or quietly (message "%s is correct" (funcall ispell-format-word-function word)))) ((stringp poss) (or quietly (message "%s is correct because of root %s" (funcall ispell-format-word-function word) (funcall ispell-format-word-function poss)))) ((null poss) (message "Error checking word %s using %s with %s dictionary" (funcall ispell-format-word-function word) (file-name-nondirectory ispell-program-name) (or ispell-current-dictionary "default"))) (ispell-check-only (progn (beep) (message "%s is incorrect" (funcall ispell-format-word-function word)))) (t (let ((wconfig ...)) (unwind-protect (progn ...) (set-window-configuration wconfig))) (cond ((equal 0 replace) (ispell-add-per-file-word-list ...)) (replace (setq new-word ... cursor-location ...) (if ... ...) (if ... ...))) (if (get-buffer ispell-choices-buffer) (kill-buffer ispell-choices-buffer)))) (ispell-pdict-save ispell-silently-savep) (if ispell-quit (setq ispell-quit nil replace (quote quit))) (goto-char cursor-location) replace)))
>   ispell-word(nil nil nil t)
>   funcall-interactively(ispell-word nil nil nil t)
>   call-interactively(ispell-word nil nil)
>   #f(compiled-function (cmd &optional record-flag keys special) "Execute CMD as an editor command.\nCMD must be a symbol that satisfies the `commandp' predicate.\nOptional second arg RECORD-FLAG non-nil\nmeans unconditionally put this command in the variable `command-history'.\nOtherwise, that is done only if an arg is read using the minibuffer.\nThe argument KEYS specifies the value to use instead of (this-command-keys)\nwhen reading the arguments; if it is nil, (this-command-keys) is used.\nThe argument SPECIAL, if non-nil, means that this command is executing\na special event, so ignore the prefix argument and don't clear it." #<bytecode 0x20c9b7f>)(ispell-word nil nil nil)
>   ad-Advice-command-execute(#f(compiled-function (cmd &optional record-flag keys special) "Execute CMD as an editor command.\nCMD must be a symbol that satisfies the `commandp' predicate.\nOptional second arg RECORD-FLAG non-nil\nmeans unconditionally put this command in the variable `command-history'.\nOtherwise, that is done only if an arg is read using the minibuffer.\nThe argument KEYS specifies the value to use instead of (this-command-keys)\nwhen reading the arguments; if it is nil, (this-command-keys) is used.\nThe argument SPECIAL, if non-nil, means that this command is executing\na special event, so ignore the prefix argument and don't clear it." #<bytecode 0x20c9b7f>) ispell-word)
>   apply(ad-Advice-command-execute #f(compiled-function (cmd &optional record-flag keys special) "Execute CMD as an editor command.\nCMD must be a symbol that satisfies the `commandp' predicate.\nOptional second arg RECORD-FLAG non-nil\nmeans unconditionally put this command in the variable `command-history'.\nOtherwise, that is done only if an arg is read using the minibuffer.\nThe argument KEYS specifies the value to use instead of (this-command-keys)\nwhen reading the arguments; if it is nil, (this-command-keys) is used.\nThe argument SPECIAL, if non-nil, means that this command is executing\na special event, so ignore the prefix argument and don't clear it." #<bytecode 0x20c9b7f>) ispell-word)
>   command-execute(ispell-word)

**Comment by mina86** [comment]
Could you post exact steps to reproduce? I must admit your report got me
a bit confused.  Also, could you include version of your Emacs? You can
get that with `C-u M-x emacs-version RET`.

**Comment by xkix** [comment]
just enter a wrong spelled word, say `errox` then press `M-$` which calls `ispell-word`
i'm using
_Emacs: GNU Emacs 26.3 (build 1, x86_64-w64-mingw32) of 2019-08-29_ on _Win 10_

**Comment by mina86** [comment]
Once MELPA picks up the change this should be fixed. You can also get the new version directly from the library. Please reopen if the issue continues with 2.0.3 version (i.e. something past 20200801 on MELPA).

**Comment by xkix** [comment]
Works!
Thanks a lot.
