### ISSUE TITLE
In leuven theme code blocks background not changing color

### ISSUE THREAD

**Issue by fkgruber** [mina86/auto-dim-other-buffers.el#24]
Hi
I'm using the leuven theme which in org files uses a different background color for code blocks. Auto dim is not changing the background of the code block.

This is a problem because if the windows is only showing the inside of a code block then you don't see any change.
Is there a property in auto-dim to change the code block background  as well? I don't see the org-block property which is usually used to change the code block background (see https://stackoverflow.com/questions/44811679/orgmode-change-code-block-background-color)

With focus on the top window:
![image](https://user-images.githubusercontent.com/4311763/98956926-9bc25800-24ce-11eb-953c-25c4d8fa46ca.png)
with focus on the bottom window
![image](https://user-images.githubusercontent.com/4311763/98956980-ac72ce00-24ce-11eb-9f94-c3fa70586047.png)

**Comment by mina86** [comment]
If you’re using Emacs 27 (or later) this should be possible to accomplish. In that version, adob uses `adob--dim` window parameter to decide whether to dim a window or not. (You can test if this is being used by showing the same buffer in two different windows and checking if only one of them is undimmed).

However, I honestly don’t understand faces and cannot get this to work. I’m trying something like below:
```
(face-spec-set
 'org-block
 '((t (:filtered (:window adob--dim ()) :background "red")
      (:filtered (:window adob--dim t) :background "blue"))))
```
This should use red background on selected window and blue on dimmed but in reality it doesn’t do anything. With only one `:filtered` entry, given background is always used.

**Comment by mina86** [comment]
Sorry it took so long. It should work now out of the box, i.e. `org-block` is handled by default. Any additional faces may be configured by changing a new `auto-dim-other-buffers-affected-faces` list.
