### ISSUE TITLE
Making fringes dim as well

### ISSUE THREAD

**Issue by titibandit** [mina86/auto-dim-other-buffers.el#27]
Hey,
I'm trying to get the fringes to dim as well when unfocused.
Right now, using the package unmodified, I have this behavior:
![bad](https://i.ibb.co/fkbGpwV/bad.gif)
The fringes are correctly set only for the initial window that was selected (the one on the right in that case). As soon as I change window focus, fringes are messed up.

I tried to implement the good behavior by adding
```
(face-remap-add-relative 'fringe adob--remap-face)
```
to the `adob--remap-face` function, but to no avail.
I could get it to work by cycling the `fringe-mode` in the `abod--update` function:
```
...
        (when (and (window-live-p adob--last-window)
                   (not (window-minibuffer-p adob--last-window)))
          (set-window-parameter adob--last-window 'adob--dim t)
          (force-window-update adob--last-window))
        (setq adob--last-window wnd)
        (unless (window-minibuffer-p adob--last-window)
          (set-window-parameter adob--last-window 'adob--dim nil)
          (force-window-update adob--last-window)
					(fringe-mode 0)
					(fringe-mode nil)))
...
```
As you can see here:
![good](https://i.ibb.co/0CL2LNP/good.gif)

However, cycling the fringe-mode is a little bit laggy: switching windows is not as fluid.
So I wonder if there is a more efficient way of doing this?
Cheers,

**Comment by mina86** [comment]
My first guess is that we need to tell Emacs that fringes need to be refreshed somewhere similarly to how `force-window-update` is called. That’s just speculation though.

**Comment by mina86** [comment]
```
(defun adob--force-update (object)
  (force-window-update object)
  ;; Force fringes to be updated
  (when fringe-mode
    (dolist (wnd (if (windowp object)
                     (list object)
                   (get-buffer-window-list object nil t)))
      (let* ((frame  (window-frame wnd))
             (params (frame-parameters frame))
             (left   (alist-get 'left-fringe  params))
             (right  (alist-get 'right-fringe params)))
        (when (and left right)
          (modify-frame-parameters
           frame '((left-fringe nil) (right-fringe nil)))
          (modify-frame-parameters
           frame `((left-fringe . ,left) (right-fringe . ,right))))))))
```
with all calls to `force-window-update` replaced by calls to
`adob--force-update` seems to be doing the trick.  It is rather
inelegant function though and definitely not what we should be doing.

**Comment by titibandit** [comment]
I've recently tried some more to look into this issue, but I really don't see a better solution as what we mentioned already. I don't see a more lightweight way to selectively change the background's color of a fringe. I'll settle for the time being with deactivating the fringes on my setup.

**Comment by mina86** [comment]
It looks like what happens is that fringes are refreshed lazily and rather than being fully redrawn part of the rendered fringes are copied rather than painted again. You can get a window to state where different parts of the fringe have different colour.

**Comment by mina86** [comment]
I’ve pushed to https://github.com/mina86/auto-dim-other-buffers.el/tree/fringes version which seems to be working.

**Comment by titibandit** [comment]
Hey,
thanks for fixing this after all this time, it works really well! I don't even have flicker or anything of the sort.
Just a comment: why did you set by default the `fringe` entry in `auto-dim-other-buffers-affected-faces` to `(auto-dim-other-buffers-face . mode-line-active)`? The effect is that, when active, the current window will have its fringes have the same color as the mode-line, which is rather unexpected? In my case, I rather have the fringe color set to whatever my theme sets it to. I reckon this is the case for most users as well. I can of course customize that value to `(auto-dim-other-buffers-face . nil)` easily, but it might be good to have it be the default?
Thanks again.
Cheers.

**Comment by mina86** [comment]
My first idea was to only highlight the fringe in selected window rather than dimming it in non-selected windows. Eventually I’ve also done the latter. But you’re right, at this point the net effect is that the actual fringe face is never used. I’ll push a fix shortly.

**Comment by mina86** [comment]
Actually, this made me realise that a *much* simpler way to implement this is to use `fringe` as the dim face.

    (setq auto-dim-other-buffers-affected-faces
          '((default   . (fringe . nil))
            (org-block . (fringe . nil))
            (org-hide  . (auto-dim-other-buffers-hide . nil))))

Now only `auto-dim-other-buffers-hide` needs to be adjusted.

**Comment by titibandit** [comment]
> Though this may look bad if users have funky `fringe` face.
That's true. Even in my case, I actually want the fringe to have the same colour as the background. So using this would produce no effect on my setup.
