### ISSUE TITLE
problems with load-theme after enabling adob

### ISSUE THREAD

**Issue by nrvale0** [mina86/auto-dim-other-buffers.el#28]
I've noticed that after loading auto-dim-other-buffer I start getting error messages from load-theme:
    
    (use-package auto-dim-other-buffers
       :config
       (auto-dim-other-buffers-mode 1))

Error:

    eval: Symbol’s function definition is void: t

It does appear as though load-theme is working as expected though so not sure what to make of this. 

I will try running with debug-on-error later but I'm not an elisp expert.

**Comment by mina86** [comment]
I cannot reproduce it sadly. Output of `debug-on-error` or reproduction steps would be helpful.

**Comment by nrvale0** [comment]
Hmm...was getting the same after a couple of restarts but I just restarted several times and now I cannot repro.

If I can't repro in the next day or two I will close this out.

**Comment by nrvale0** [comment]
After a straight-pull-all this seems to have sorted itself out. Closing. Thx.
