### ISSUE TITLE
Don't Dim Helm Menus

### ISSUE THREAD

**Issue by rnikoopour** [mina86/auto-dim-other-buffers.el#29]
Hello,

Would it be possible to not dim the menu's created by Helm?  

For example it'd be nice if  using `helm-M-x`  dimmed everything but the minibuffer and the helm completion menu.

I haven't started digging into how to achieve this, but I'd be happy to contribute.

**Comment by mina86** [comment]
There’s a `auto-dim-other-buffers-never-dim-buffer-functions` hook
which can be used for that. I’ve never used helm but the following
might work:

    ;; Never dim helm menu buffers, i.e. buffers whose name starts
    ;; with "*helm"
    (defun mpn-never-dim-helm (buf)
      (string-prefix-p "*helm" (buffer-name buf)))
    (add-hook 'auto-dim-other-buffers-never-dim-buffer-functions
              #'mpn-never-dim-helm)

**Comment by rnikoopour** [comment]
Awesome that definitely works.  

If you're open to it I'd like to submit an MR to expose this more readily through `auto-dim-other-buffers` by exposing `(defcustom auto-dim-other-buffers-ignore-helm...`

**Comment by mina86** [comment]
To be honest I’d rather not end up having dozens of `auto-dim-other-buffers-ignore-foo` variables.  For example Magit has similar issue from what I understand and it would end up needing another customise.  And there are likely many more examples.  It’d be great if the defaults worked for majority of cases, but I’d prefer something that doesn’t fan out so much.
