### ISSUE TITLE
Dim org-mode's headings leading stars

### ISSUE THREAD

**Issue by titibandit** [mina86/auto-dim-other-buffers.el#30]
In an org-mode file, you can "hide" the leading stars of a heading, by using the org-hide face. The foreground of this face is supposed to be equal to the background of the frame, this way, the leading stars won't be visible.
Only thing is that, with auto-dim, the background color of the frame changes, while the org-hide face doesn't change.
I could make it work, as you can see here: https://git.titibandit.eu/thibaut/auto-dim-other-buffers.el/commit/047280b3735a1c351f4bbe4f22cad47938e70b89
But there, I've hardcoded the color of my background, I'm not sure how I can automatically retrieve the dimmed background color. When this is achieved, maybe we can merge this in here?

For reference, without the fix, dimmed org-mode buffers look like this:
![Org hide](https://i.ibb.co/zr0VNJV/org-hide.png)

**Comment by mina86** [comment]
Sorry it took so long. I’ve added `auto-dim-other-buffers-hide-face` in the most recent release (soon available on MELPA I’m guessing). Once it’s customised such that it’s foreground and background match desired dimmed background, `org-hide` will work with no further issues. Any other faces which need similar treatment can be added by editing `auto-dim-other-buffers-affected-faces` list.
