### ISSUE TITLE
apply: Wrong number of arguments: #<subr adob--kill-all-local-variables-advice>, 2

### ISSUE THREAD

**Issue by indigoviolet** [mina86/auto-dim-other-buffers.el#32]
When installed from melpa, with emacs 29.0.50 (built from source), doom-emacs running in sandbox without any doom modules/personal config except `auto-dim-other-buffers`, I see this error after enabling `auto-dim-other-buffers-mode`. Have you seen this previously?

`apply: Wrong number of arguments: #<subr adob--kill-all-local-variables-advice>, 2`

**Comment by mina86** [comment]
Thanks for the report. Melpa should pick the fix up soon.

**Comment by indigoviolet** [comment]
Thanks for the super quick fix!!
