### ISSUE TITLE
vterm buffers not dimming

### ISSUE THREAD

**Issue by egr95** [mina86/auto-dim-other-buffers.el#35]
Thanks for this awesome package!

Was wondering if it is possible to get the dimming to work on vterm buffers? As far as I can tell, if one of your window splits is a vterm buffer, the background color of that buffer will not change when you jump in and out of that window.

**Comment by mina86** [comment]
I took a quick look and it appears vterm doesn’t support face remapping (mind you, I haven’t looked at vterm’s code so I could be wrong).

**Comment by egr95** [comment]
Shame, thanks for taking a look!

**Comment by lrustand** [comment]
For anyone else having this problem, just add the following to your init.el:

 ```
 (defun old-version-of-vterm--get-color (index &rest args)
    "This is the old version before it was broken by commit
https://github.com/akermu/emacs-libvterm/commit/e96c53f5035c841b20937b65142498bd8e161a40.
Re-introducing the old version fixes auto-dim-other-buffers for vterm buffers."
    (cond
     ((and (>= index 0) (< index 16))
      (face-foreground
       (elt vterm-color-palette index)
       nil 'default))
     ((= index -11)
      (face-foreground 'vterm-color-underline nil 'default))
     ((= index -12)
      (face-background 'vterm-color-inverse-video nil 'default))
     (t
      nil)))
  (advice-add 'vterm--get-color :override #'old-version-of-vterm--get-color)

```

**Comment by getong** [comment]
> For anyone else having this problem, just add the following to your init.el:
> 
> ```
> (defun old-version-of-vterm--get-color (index &rest args)
>    "This is the old version before it was broken by commit
> https://github.com/akermu/emacs-libvterm/commit/e96c53f5035c841b20937b65142498bd8e161a40.
> Re-introducing the old version fixes auto-dim-other-buffers for vterm buffers."
>    (cond
>     ((and (>= index 0) (< index 16))
>      (face-foreground
>       (elt vterm-color-palette index)
>       nil 'default))
>     ((= index -11)
>      (face-foreground 'vterm-color-underline nil 'default))
>     ((= index -12)
>      (face-background 'vterm-color-inverse-video nil 'default))
>     (t
>      nil)))
>  (advice-add 'vterm--get-color :override #'old-version-of-vterm--get-color)
> ```

Thanks

**Comment by egr95** [comment]
Very nice, thank you @lrustand !
