### ISSUE TITLE
Configure the background color declaratively

### ISSUE THREAD

**Issue by juboba** [mina86/auto-dim-other-buffers.el#36]
I would like to customize the background color in my doom emacs config (can't use customize- functions).
I guess two variables would need to be configured, for light and dark themes, right?

**Comment by mina86** [comment]
You need to customise auto-dim-other-buffers-face face (and auto-dim-other-buffers-hide-face if you’re using org-mode). If you have multiple themes you may need to customise it for each theme.

**Comment by juboba** [comment]
🤔 I'm also using `auto-dark-theme` to sync emacs them to the system
```emacs-lisp
(setq! auto-dark-dark-theme 'kaolin-ocean
        auto-dark-light-theme 'doom-nord-light)
```

I was hoping I could to something like:
```emacs-lisp
(setq auto-dim-other-buffers-face '(background light) :background [light color]) (t :background [dark color]))
```

or something like that based on what you have for deffface.

```emacs-lisp
(defface auto-dim-other-buffers-face
  '((((background light)) :background "#eff") (t :background "#122"))
  "Face with a (presumably) dimmed background for non-selected window.

By default the face is applied to, among others, the ‘default’
face and is intended to affect the background of the non-selected
windows.  A related ‘auto-dim-other-buffers-hide-face’ face is
intended for faces which need their foreground to be changed in
sync.  Which faces are actually modified is configured by the
‘auto-dim-other-buffers-affected-faces’ variable."
  :group 'auto-dim-other-buffers)
```

I don't know much about faces in emacs, so I would appreciate the help.
Btw, thank a lot for this package @mina86, I would love to use it when sharing screen so my colleagues know what's the active window.

**Comment by mina86** [comment]
I don’t know much about themes, but I imagine you’d have to add the face to the two themes.

**Comment by juboba** [comment]
thank you @mina86 I will try that
