### ISSUE TITLE
When scrolling backwards, auto-dim-other-buffers gets enabled

### ISSUE THREAD

**Issue by ReneFroger** [mina86/auto-dim-other-buffers.el#8]
When I'm scrolling inside a buffer, I'm often wondering: where the fuck am I
now?! 

For that I use the plugin
[Smooth scroll](http://www.emacswiki.org/emacs/smooth-scroll.el) to make visible
in which direction I'm heading. 

However, when scrolling backwards, I found that it enables the face of the
`auto-dim-other-buffers`. You can test it with my configuration:

    (require 'smooth-scroll) 
    (smooth-scroll-mode 1)
    (setq smooth-scroll/vscroll-step-size 5)

    (defun window-half-height ()
    (max 1 (/ (1- (window-height (selected-window))) 2)))
    
    ;;;###autoload
    (defun own-scroll-up-half ()
        (interactive)
        (next-line (window-half-height))
        (scroll-up (window-half-height)))

    ;;;###autoload
    (defun own-scroll-down-half ()         
        (interactive)                    
        (previous-line (window-half-height))
        (scroll-down (window-half-height)))

Bind then a key to the own-scroll-down-half, in order to scroll up. The weird
thing is that I don't get the `auto-dim-other-buffers` face when I'm scrolling down.

**Comment by mina86** [comment]
I actually cannot reproduce the problem you are describing. Both commands work fine for me. Have you tried recent Emacs?

**Comment by ReneFroger** [comment]
Perhaps it's related to my configuration then. Since it's seems to be related with my own configuration (you said you cannot reproduce it), I will close this issue then. Thanks for your reply!
